services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tourze\ProductCollectBundle\DataFixtures\ProductCollectFixtures:
        public: true
        tags:
            - { name: doctrine.fixture.orm }